#!/usr/bin/env node
/**
 * build-data.mjs — the heart of the "data is not code" principle.
 *
 * Reads data/uganda.csv (falling back to data/uganda.sample.csv), builds the
 * flat structure-of-arrays tree, and emits one generated module per level:
 *
 *   src/generated/{districts,counties,subcounties,parishes,villages}.ts
 *
 * Each module is `export default JSON.parse("...")` — the string is parsed
 * by V8's JSON fast path (faster than evaluating an object literal) and the
 * pattern works in every bundler with no import-attribute support needed.
 *
 * Invariants this script guarantees (the runtime relies on them):
 *   1. Within each level, units are sorted by (parentIndex, name).
 *   2. Therefore all children of a parent are CONTIGUOUS.
 *   3. spans[parentId] = [firstChildIndex, childCount] into the child level.
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const pkgRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const fullCsv = join(pkgRoot, "data", "uganda.csv");
const sampleCsv = join(pkgRoot, "data", "uganda.sample.csv");

// Optional overrides (used by the scale benchmark):
//   node build-data.mjs --csv <path> --out <dir>
const argv = process.argv.slice(2);
const argOf = (flag) => {
  const i = argv.indexOf(flag);
  return i >= 0 ? argv[i + 1] : undefined;
};
const csvPath = argOf("--csv") ?? (existsSync(fullCsv) ? fullCsv : sampleCsv);
const outDir = argOf("--out") ?? join(pkgRoot, "src", "generated");

const pkg = JSON.parse(readFileSync(join(pkgRoot, "package.json"), "utf8"));
const VERSION = pkg.ugkit?.datasetVersion ?? "0.0.0";

const LEVELS = ["districts", "counties", "subcounties", "parishes", "villages"];

// ---------------------------------------------------------------- parse CSV
// Minimal CSV parsing: our pipeline controls the file, names contain no
// commas/quotes. If the sourced dataset ever does, upgrade this first.
const lines = readFileSync(csvPath, "utf8").trim().split("\n");
const header = lines.shift();
if (header !== "district,county,subcounty,parish,village") {
  throw new Error(`Unexpected CSV header: ${header}`);
}

// Rows may be VARIABLE DEPTH: a row populates levels 0..depth-1 and stops.
// This lets us ship a shallow dataset (e.g. district+county) and back-fill
// deeper levels later, without a schema change. Absent levels emit empty blobs.
// A row must have a non-empty leading run and NO interior gaps.
const rows = lines.map((l) => {
  const cells = l.split(",").map((s) => s.trim());
  let depth = 0;
  while (depth < cells.length && cells[depth]) depth++;
  if (depth === 0) throw new Error(`Bad row (empty district): ${JSON.stringify(l)}`);
  for (let i = depth; i < cells.length; i++) {
    if (cells[i]) throw new Error(`Bad row (interior gap): ${JSON.stringify(l)}`);
  }
  return cells.slice(0, depth); // keep only the populated prefix
});

// ------------------------------------------------- build the tree, level 0→4
// nodesPerLevel[L] = Map<pathKey, { name, parentKey }>
// pathKey uniquely identifies a unit by its full ancestry, because names
// repeat across parents (many districts have a "Central" division).
const SEP = "\u0000";
const nodesPerLevel = LEVELS.map(() => new Map());

for (const row of rows) {
  let parentKey = "";
  for (let L = 0; L < row.length; L++) {
    const key = parentKey + SEP + row[L];
    if (!nodesPerLevel[L].has(key)) {
      nodesPerLevel[L].set(key, { name: row[L], parentKey });
    }
    parentKey = key;
  }
}

// -------------------------------------- assign indices: sort, then span-index
// prevIndexByKey maps a parent's pathKey → its final index in its level.
let prevIndexByKey = new Map();
let prevCount = 0;

mkdirSync(outDir, { recursive: true });

for (let L = 0; L < 5; L++) {
  const entries = [...nodesPerLevel[L].entries()].map(([key, node]) => ({
    key,
    name: node.name,
    parent: L === 0 ? -1 : prevIndexByKey.get(node.parentKey),
  }));

  // Invariant 1: sort by (parent, name) → Invariant 2: children contiguous.
  entries.sort((a, b) => a.parent - b.parent || a.name.localeCompare(b.name));

  const names = entries.map((e) => e.name);
  const parents = entries.map((e) => e.parent);

  // Invariant 3: spans for THIS level, keyed by parent index in level above.
  const spans = Array.from({ length: prevCount }, () => [0, 0]);
  for (let i = 0; i < entries.length; i++) {
    const p = entries[i].parent;
    if (p < 0) continue;
    if (spans[p][1] === 0) spans[p][0] = i;
    spans[p][1]++;
  }

  const blob = { version: VERSION, names, parents, spans };
  const json = JSON.stringify(blob);
  const out =
    `// GENERATED by scripts/build-data.mjs from ${csvPath.endsWith("sample.csv") ? "SAMPLE data" : "uganda.csv"} — do not edit.\n` +
    `// dataset ${VERSION} · ${names.length} units\n` +
    `export default JSON.parse(${JSON.stringify(json)});\n`;

  writeFileSync(join(outDir, `${LEVELS[L]}.ts`), out);
  console.log(`${LEVELS[L].padEnd(12)} ${String(names.length).padStart(6)} units`);

  prevIndexByKey = new Map(entries.map((e, i) => [e.key, i]));
  prevCount = entries.length;
}

console.log(`\nDataset ${VERSION} built from ${csvPath}`);
if (csvPath === sampleCsv) {
  console.log("⚠ Using SAMPLE data. Place the full dataset at data/uganda.csv.");
}
